spring.application.name=reservation

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/reservation

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

#구글 oauth2.0 oidc
spring.security.oauth2.client.registration.google.client-id=1078988144435-ophc0o2idfj9spgup0dde8qo3kp810rn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid, email, profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v3/userinfo

logging.level.org.springframework.security=DEBUG